=== ravitejadevloper/ltts/SmartRV/main_service/components/schemas/ComponentGroups_$schema.json
{
    "$schema": "http://json-schema.org/schema",
    "properties": {
        "$schema": {
            "type": "string"
        },
        "id": {
            "description": "unique identifier including category and modifier",
            "type": "string"
        },
        "description": {
            "description": "description",
            "type": "string"
        },
        "type": {
            "description": "type",
            "type": "string",
            "enum": [
                "componentGroup"
            ]
        },
        "deviceType": {
            "description": "device Type - core if multiple device types, otherwise target device type",
            "type": "string",
            "default": "core"
        },
        "seriesModel": {
            "description": "seriesModel",
            "type": "string"
        },
        "floorPlan": {
            "description": "floorPlan",
            "type": "string"
        },
        "filters": {
            "type": "object",
            "description": "filters - key with string array values",
            "patternProperties": {
                "^.*$": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "attributes": {
            "type": "object",
            "description": "component group attributes",
            "patternProperties": {
                "^.*$": {
                    "type": "string"
                }
            }
        },
        "optionCodes": {
            "type": "array",
            "description": "optionCodes",
            "items": {
                "type": "string"
            }
        },
        "components": {
            "description": "components",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "componentTypeId": {
                        "type": "string",
                        "description": "componentTypeId"
                    },
                    "instance": {
                        "type": "integer",
                        "description": "instance"
                    },
                    "attributes": {
                        "type": "object",
                        "description": "component attributes",
                        "patternProperties": {
                            "^.*$": {
                                "anyOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "boolean"
                                    },
                                    {
                                        "type": "integer"
                                    },
                                    {
                                        "type": "number"
                                    },
                                    {
                                        "type": "array",
                                        "items": {
                                            "anyOf": [
                                                {
                                                    "type": "boolean"
                                                },
                                                {
                                                    "type": "string"
                                                },
                                                {
                                                    "type": "integer"
                                                },
                                                {
                                                    "type": "object"
                                                },
                                                {
                                                    "type": "number"
                                                }
                                            ]
                                        }
                                    }
                                ]
                            }
                        }
                    },
                    "relatedComponents": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "componentTypeId": {
                                    "type": "string"
                                },
                                "instance": {
                                    "type": "integer"
                                }
                            },
                            "required": [
                                "componentTypeId",
                                "instance"
                            ]
                        }
                    },
                    "filters": {
                        "type": "object",
                        "description": "filters",
                        "patternProperties": {
                            "^.*$": {
                                "type": "string",
                                "description": "regex filter"
                            }
                        }
                    },
                    "meta": {
                        "type": "object",
                        "description": "meta information",
                        "properties": {
                            "manufacturer": {
                                "type": "string"
                            },
                            "part": {
                                "type": "string"
                            },
                            "model": {
                                "type": "string"
                            }
                        },
                        "patternProperties": {
                            "^.*$": {
                                "anyOf": [
                                    {
                                        "type": "string"
                                    }
                                ]
                            }
                        },
                        "required": [
                            "manufacturer",
                            "part",
                            "model"
                        ],
                        "additionalProperties": true
                    }
                },
                "required": [
                    "componentTypeId",
                    "instance",
                    "attributes"
                ]
            }
        }
    },
    "required": [
        "id",
        "type",
        "deviceType",
        "components"
    ],
    "additionalProperties": false
}

=== ravitejadevloper/ltts/SmartRV/data/vanilla.vanilla.VANILLA.componentGroup.json
{
    "$schema": "./$schema.json",
    "id": "vanilla.vanilla.VANILLA",
    "type": "componentGroup",
    "description": "component groups allow us to piece together rv components based on its device type, model, floorplan starting with lowest to greatest specificity",
    "deviceType": "vanilla",
    "seriesModel": "vanilla",
    "floorPlan": "VANILLA",
    "attributes": {
        "name": "Vanilla Manufacturing Floorplan",
        "seriesName": "VANILLA",
        "seriesCode": "vanilla",
        "version": "1.0.0"
    },
    "optionCodes": [],
    "filters": {},
    "components": []
}
